"""Initial migration

Revision ID: c82b4f2d2ea3
Revises: 
Create Date: 2024-01-04 00:15:47.053031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c82b4f2d2ea3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmenttype',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspectiontargettype',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspectiontype',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('location',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('zip_code', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('role', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('access_token_identifier', sa.String(length=45), nullable=True),
    sa.Column('refresh_token_identifier', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('environment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('environmenttype_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['environmenttype_id'], ['environmenttype.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_environmenttype_id'), 'environment', ['environmenttype_id'], unique=False)
    op.create_index(op.f('ix_environment_location_id'), 'environment', ['location_id'], unique=False)
    op.create_table('inspectiontarget',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('environment_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('inspectiontargettype_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['inspectiontargettype_id'], ['inspectiontargettype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectiontarget_environment_id'), 'inspectiontarget', ['environment_id'], unique=False)
    op.create_index(op.f('ix_inspectiontarget_inspectiontargettype_id'), 'inspectiontarget', ['inspectiontargettype_id'], unique=False)
    op.create_table('userresponsibleenvironment',
    sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('environment_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'environment_id')
    )
    op.create_index(op.f('ix_userresponsibleenvironment_environment_id'), 'userresponsibleenvironment', ['environment_id'], unique=False)
    op.create_index(op.f('ix_userresponsibleenvironment_user_id'), 'userresponsibleenvironment', ['user_id'], unique=False)
    op.create_table('inspectionform',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('closedAt', sa.DateTime(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('environment_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('inspectiontarget_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('inspectiontype_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['inspectiontarget_id'], ['inspectiontarget.id'], ),
    sa.ForeignKeyConstraint(['inspectiontype_id'], ['inspectiontype.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectionform_environment_id'), 'inspectionform', ['environment_id'], unique=False)
    op.create_index(op.f('ix_inspectionform_inspectiontarget_id'), 'inspectionform', ['inspectiontarget_id'], unique=False)
    op.create_index(op.f('ix_inspectionform_inspectiontype_id'), 'inspectionform', ['inspectiontype_id'], unique=False)
    op.create_index(op.f('ix_inspectionform_user_id'), 'inspectionform', ['user_id'], unique=False)
    op.create_table('instruction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updateAt', sa.DateTime(), nullable=True),
    sa.Column('inspectiontarget_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('updated_by', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inspectiontarget_id'], ['inspectiontarget.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruction_created_by'), 'instruction', ['created_by'], unique=False)
    op.create_index(op.f('ix_instruction_inspectiontarget_id'), 'instruction', ['inspectiontarget_id'], unique=False)
    op.create_index(op.f('ix_instruction_updated_by'), 'instruction', ['updated_by'], unique=False)
    op.create_table('userresponsibletarget',
    sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('inspectiontarget_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['inspectiontarget_id'], ['inspectiontarget.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'inspectiontarget_id')
    )
    op.create_index(op.f('ix_userresponsibletarget_inspectiontarget_id'), 'userresponsibletarget', ['inspectiontarget_id'], unique=False)
    op.create_index(op.f('ix_userresponsibletarget_user_id'), 'userresponsibletarget', ['user_id'], unique=False)
    op.create_table('file',
    sa.Column('id', mysql.INTEGER(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('random_name', sa.String(length=255), nullable=False),
    sa.Column('inspectionform_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['inspectionform_id'], ['inspectionform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_inspectionform_id'), 'file', ['inspectionform_id'], unique=False)
    op.create_index(op.f('ix_file_random_name'), 'file', ['random_name'], unique=False)
    op.create_table('inspectionresult',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('value', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('inspectionform_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['inspectionform_id'], ['inspectionform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectionresult_inspectionform_id'), 'inspectionresult', ['inspectionform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspectionresult_inspectionform_id'), table_name='inspectionresult')
    op.drop_table('inspectionresult')
    op.drop_index(op.f('ix_file_random_name'), table_name='file')
    op.drop_index(op.f('ix_file_inspectionform_id'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_userresponsibletarget_user_id'), table_name='userresponsibletarget')
    op.drop_index(op.f('ix_userresponsibletarget_inspectiontarget_id'), table_name='userresponsibletarget')
    op.drop_table('userresponsibletarget')
    op.drop_index(op.f('ix_instruction_updated_by'), table_name='instruction')
    op.drop_index(op.f('ix_instruction_inspectiontarget_id'), table_name='instruction')
    op.drop_index(op.f('ix_instruction_created_by'), table_name='instruction')
    op.drop_table('instruction')
    op.drop_index(op.f('ix_inspectionform_user_id'), table_name='inspectionform')
    op.drop_index(op.f('ix_inspectionform_inspectiontype_id'), table_name='inspectionform')
    op.drop_index(op.f('ix_inspectionform_inspectiontarget_id'), table_name='inspectionform')
    op.drop_index(op.f('ix_inspectionform_environment_id'), table_name='inspectionform')
    op.drop_table('inspectionform')
    op.drop_index(op.f('ix_userresponsibleenvironment_user_id'), table_name='userresponsibleenvironment')
    op.drop_index(op.f('ix_userresponsibleenvironment_environment_id'), table_name='userresponsibleenvironment')
    op.drop_table('userresponsibleenvironment')
    op.drop_index(op.f('ix_inspectiontarget_inspectiontargettype_id'), table_name='inspectiontarget')
    op.drop_index(op.f('ix_inspectiontarget_environment_id'), table_name='inspectiontarget')
    op.drop_table('inspectiontarget')
    op.drop_index(op.f('ix_environment_location_id'), table_name='environment')
    op.drop_index(op.f('ix_environment_environmenttype_id'), table_name='environment')
    op.drop_table('environment')
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('inspectiontype')
    op.drop_table('inspectiontargettype')
    op.drop_table('environmenttype')
    # ### end Alembic commands ###
